[supervisord]
nodaemon=true

[program:php-fpm]
command=/usr/sbin/php-fpm7.4 -F
autostart=true
autorestart=true
priority=5

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true
priority=10

[program:fixperm]
command=/bin/sh -c "if [ ! -f /tmp/fixperm.done ]; then echo '首次启动：sleep 60准备chown'; sleep 60; chown -R 33:33 /data  /user-files /file /filerun /files; echo 'chown完成，写入锁文件'; touch /tmp/fixperm.done; else echo '锁文件已存在，跳过权限修复'; fi"
autostart=true
autorestart=false
startsecs=0
priority=15
redirect_stderr=true
stdout_logfile=/var/log/fixperm.log
